name: Test SSH Proxmox LXC

on: [push]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROXMOX_HOST }}  # IP du conteneur
          username: root
          key: ${{ secrets.PROXMOX_SSH_KEY }}
          script: "echo 'Connexion SSH réussie avec GitHub Actions !'"
